### PR TITLE
Add tls flag

### PR DESCRIPTION
**Pull request by adamnoll**

### CODE REVIEW

**Comment by adamnoll** [comment]
Updated from kops/master and added the new flag

**Comment by valdisrigdon** [comment]
Shouldn't this be updated from `release-1.11` not `kops/master`?

**Comment by adamnoll** [comment]
@valdisrigdon normally that would be correct, but after looking at the changes that are in kops/master and kops/release-1.11, I decided to just grab master. Most of the fixes in master were typos and flags... if we are building our own version of 1.11, I figured its best to grab those fixes

**Comment by valdisrigdon** [comment]
I guess that's ok? Seems like it might be harder to maintain then because now we only have to forward patch these two commits.

**Pull request merged**
